// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MuniDbContext))]
    [Migration("20250824001751_addTwoOperators")]
    partial class addTwoOperators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("Domain.Entities.Operator", b =>
                {
                    b.Property<int>("DNI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NLegajo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("DNI");

                    b.ToTable("Operators");

                    b.HasData(
                        new
                        {
                            DNI = 46502865,
                            Deleted = 0,
                            Email = "micaela@example.com",
                            LastName = "Ortigoza",
                            NLegajo = 459850,
                            Name = "Micaela",
                            Password = "123abc",
                            Phone = "3416897542",
                            Position = 3
                        },
                        new
                        {
                            DNI = 43567210,
                            Deleted = 0,
                            Email = "lucas@example.com",
                            LastName = "Fernandez",
                            NLegajo = 459851,
                            Name = "Lucas",
                            Password = "abc12345",
                            Phone = "3416549871",
                            Position = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
